# Generated by Django 5.0.6 on 2024-06-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_api', '0003_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='news_source',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
